apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::605241751705:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::605241751705:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WLBJVP4S2KMA
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-24T18:23:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "44236"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 19cc41a3-9109-4884-8fa6-ecf07ebd5e8b
